### ISSUE TITLE
get request doesn't close the connection

### ISSUE THREAD

**Issue by divya-s-sharma** [mariano-fiorentino/amid#10]
Hi,
We use the 'app.get('/:db/:collection/:id?', function(req, res)' but the problem is it opens the connections and doesn't close it,leaving us with even 600 open connections at certain time.
Is there a way to fix this problem.
Thanks in advance.

**Comment by mariano-fiorentino** [comment]
Hi, 
i found that the connection is not closed only in case of getting the lists of databases/collections and in some other operation.
I made a new package on npm to fix this problem.

Regards
