### ISSUE TITLE
Filter on date: possible?

### ISSUE THREAD

**Issue by jschaeke** [mariano-fiorentino/amid#11]
Hi,

I am struggling to use date filters, e.g: is it possible to query following (valid) Mongo shell query over amid?
`db.myColl.find({creationTime: { $gte : ISODate("2015-11-10T10:30:34Z")}})`

**Comment by mariano-fiorentino** [comment]
Yes, 
for example usually i do this:

http://<your-amid-installation:3000>/<your-DB>/<your-COLLECTION>/?query={%22time%22%3A{%22%24gte%22%3A%222015-11-13T00%3A00%3A00.000Z%22}}&sort={%22time%22%3A%20-1}&skip=0&limit=100 

assuming that you are searching on a field "time" that has the correct type on mongo
