### ISSUE TITLE
Ambiguous response code in post method.

### ISSUE THREAD

**Issue by divya-s-sharma** [mariano-fiorentino/amid#12]
Hi 

In the following method of rest.js
/**
 * Insert
 */
app.post('/:db/:collection', function(req, res){}

The code always returns  
"res.send('{"ok":1}', 201);" , even if the insertion failed due to any reason, hence it becomes difficult to catch any exception based on the response status.
Is it possible to return a proper response status?

Thanks in advance

**Comment by divya-s-sharma** [comment]
Hi 

I have made some change in the amid code and it now sends the proper response back, if there is any error while insertion of records.
I am not sure if everyone expects any error response back, if you think its a proper change, I could commit the changes.Also the error response should be added in probably all the operations, because we don't get properly notified if it fails.

Thanks

**Comment by mariano-fiorentino** [comment]
Hi divya-s-sharma,
thank you! I'm developing the errors management but i'm very busy with my
job in this last months. If you submit your contribution, i will be happy
to add your code in the project.

Regards,

[MF]

**Comment by divya-s-sharma** [comment]
Hi Mariano

I have proposed the code changes in amid. Are you able to see them?

Regards

**Comment by mariano-fiorentino** [comment]
Hi divya-s-sharma,
the change looks good, you can merge this patch to the master. I'll do some
checks of the new version in my environment before do the new npm.

Regards,
[MF]

**Comment by mariano-fiorentino** [comment]
Hi,
i did some changes on your management, to get errors for example also in case of db connection error, and others problem that can happen.
As soon as possible i'll made a new release.
Regards,
[MF]

**Comment by divya-s-sharma** [comment]
Hi,

Thanks for the update.Right now we are not using all the operations from rest.js but surely it would be a much needed and helpful change.

Regards,
DS
