### ISSUE TITLE
What's the correct syntax for sorting?

### ISSUE THREAD

**Issue by eddieospaghettio** [mariano-fiorentino/amid#8]
I have Amid set up here: http://54.214.110.58:8080/workshop/items/ and I can't seem to get sort to work properly.

The documentation says to use sort like this: GET /db/collection/?sort=[{"property":null,"direction":"ASC"}]

When I go here it returns results, but they're not sorted: http://54.214.110.58:8080/workshop/items/?sort={"property":itemKey,"direction":"ASC"}

Same thing happens if I try to sort by another property: http://54.214.110.58:8080/workshop/items/?sort={"property":creationDate,"direction":"ASC"}

Is my syntax just wrong? If I try this it returns no results: http://54.214.110.58:8080/workshop/items/?sort={"property":null,"direction":"ASC"}

Sorry to bug you I just didn't know where else to ask.

Thanks,
Eddie Olivas

**Comment by mariano-fiorentino** [comment]
Hi Eddie,
if you want sort by creationDay you can use this syntax:

http://54.214.110.58:8080/workshop/items/?sort={"creationDate":1}

where 1 is for desc, -1 is for asc - don't forget to make an index on creationDate.
To paging the results, for example:

http://54.214.110.58:8080/workshop/items/?sort={"creationDate":-1}&skip=100&limit=100

Means that you have ordered records starting from 101 for a length of 100.

Regards
Mariano

**Comment by eddieospaghettio** [comment]
Thanks so much!! That works perfect.

*Eddie Olivas* | Internet Marketing Revolutionary | Direct: (541) 913-2358
| eddie@chrysaliswebdevelopment.com | Skype: eddie_0livas |
www.chrysaliswebdevelopment.com <http://chrysaliswebdevelopment.com/>
