### ISSUE TITLE
sort is not working

### ISSUE THREAD

**Issue by biaggi** [mariano-fiorentino/amid#9]
I'm trying to sort a query using the url in the examples and is not working for me, no result is returned when the sort parameter is different from undefined.

http://localhost:3000/db/collection/?limit=10&skip=0&sort=[{%22property%22:null,%22direction%22:%22ASC%22}]

**Comment by mariano-fiorentino** [comment]
Hi,
have you tryed this syntax?
(example to sort by the field "creationdate", -1 is for ASC sorts, 1 means DESC sorts)

http://localhost:3000/db/collection/?sort={"creationDate":-1}&skip=0&limit=100

**Comment by biaggi** [comment]
Reading the code and some documentation, the sintax I'm looking for is this one: 

http://localhost:3000/db/collection/?limit=10&skip=0&sort=[[%22menId%22,%22ASC%22]]

http://mongodb.github.io/node-mongodb-native/1.4/markdown-docs/queries.html#sorting

Thank you for the tool anyway ;-)

**Comment by mariano-fiorentino** [comment]
Hi,
you can use this syntax (es):

http://localhost/mongo/application/essential/?_dc=1430410411567&sort={%22thread%22:1,%22message%22:1}&skip=0&limit=100

Also take a look at this post:

https://groups.google.com/forum/#!topic/nodejs/f5QUtKGwuME
